// part of this jsx and css generated by codex for animation
import { useState } from "react";
import MultiActionAreaCard from "./Card";
import "./FloatingPortfolio.css";
import repairImage from "./assets/inspiredimages-mobile-phone-1230984.jpg";
import cardsImage from "./assets/clker-free-vector-images-aces-37800.png";
import ecommerceImage from "./assets/kasjanf-girl-4181395.jpg";
import analyticsImage from "./assets/pikura-pixel-art-7280249.png";

const items = [
  {
    id: "0",
    image: repairImage,
    title: "Electronic Repair Service - Coming soon",
    label: "Electronic Repair Service - Coming soon",
    content: "Coming soon",
    position: "top",
  },
  {
    id: "1",
    image: cardsImage,
    title: "Shuffle Cards - Coming soon",
    label: "Shuffle Cards - Coming soon",
    content: "Coming soon",
    position: "right",
  },
  {
    id: "2",
    image: ecommerceImage,
    title: "E-commerce - Coming soon",
    label: "E-commerce - Coming soon",
    content: "Coming soon",
    position: "bottom",
  },
  {
    id: "3",
    image: analyticsImage,
    title: "Game analytics - Coming soon",
    label: "Game analytics - Coming soon",
    content: "Coming soon",
    position: "left",
  },
];

function FloatingPortfolio() {
  const [hoveredItem, setHoveredItem] = useState(null);

  return (
    <div className="portfolio-scene">
      <div className="center-card">
        <h2>Qingyun's Portfolio</h2>
        <hr/>
        <p>I'm studying Computer Engineering at University of Ottawa. I have a passion for software development and enjoy working on various projects.</p>
        <br/>
        <p>I'm currently taking a UI course to improve my design skills and principles.</p>
      </div>

      {items.map((item) => {
        const isOpen = hoveredItem === item.id;

        return (
          <div
            key={item.id}
            role="group"
            tabIndex={0}
            aria-label={item.label}
            className={`floating-item ${item.position} ${
              isOpen ? "active" : ""
            }`}
            onMouseEnter={() => setHoveredItem(item.id)}
            onMouseLeave={() => setHoveredItem(null)}
            onFocus={() => setHoveredItem(item.id)}
            onBlur={() => setHoveredItem(null)}
          >
            {isOpen ? (
              <MultiActionAreaCard
                image={item.image}
                label={item.label}
                title={item.title}
                content={item.content}
              />
            ) : (
              <div className="compact-card">
                <img
                  className="compact-card-image"
                  src={item.image}
                  alt={item.label}
                />
                <div className="compact-card-title">{item.title}</div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default FloatingPortfolio;
